server:
  port: 5000
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/derevenskoe}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}
  application:
    name: derevenskoe
  jpa:
    hibernate:
      ddl-auto: update