server:
  port: 80
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql:https//derevenskoe.cc9xj3w4j7hu.eu-west-3.rds.amazonaws.com:5432/derevenskoe}
    username: ${JDBC_DATABASE_USERNAME:lkVlrcWdB8RYo45C}
    password: ${JDBC_DATABASE_PASSWORD:ryRnFL4EMg3KfRabh12x}
  application:
    name: derevenskoe
  jpa:
    hibernate:
      ddl-auto: update