server:
  port: 7777
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: client
            client-secret: secret
            client-name: Bookstore
            provider: okta
            redirect-uri-template: http://localhost:7777/derevenskoe/
            client-authentication-method: basic
            authorization-grant-type: client_credentials
        provider:
          okta:
            token-uri: http://localhost:7777/oauth/token
            authorization-uri: http://localhost:7777/oauth/authorize
            user-info-uri: http://localhost:7777/users/acc
            user-name-attribute: name
  datasource:
    url: jdbc:postgresql://localhost:5432/derevenskoe
    username: postgres
    password: password
  application:
    name: derevenskoe
  jpa:
    hibernate:
      ddl-auto: update