server:
  port: 7777
spring:
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          okta:
  #            client-id: client
  #            client-secret: secret
  #            client-name: derevenskoe
  #            provider: okta
  #            redirect-uri-template: https://derevenskoe.herokuapp.com/
  #            client-authentication-method: basic
  #            authorization-grant-type: client_credentials
  #        provider:
  #          okta:
  #            token-uri: https://derevenskoe.herokuapp.com/oauth/token
  #            authorization-uri: https://derevenskoe.herokuapp.com/oauth/authorize
  #            user-info-uri: https://derevenskoe.herokuapp.com/users/validate
  #            user-name-attribute: name
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql:https//derevenskoe.cc9xj3w4j7hu.eu-west-3.rds.amazonaws.com:5432/derevenskoe}
    username: ${JDBC_DATABASE_USERNAME:lkVlrcWdB8RYo45C}
    password: ${JDBC_DATABASE_PASSWORD:ryRnFL4EMg3KfRabh12x}
  application:
    name: derevenskoe
  jpa:
    hibernate:
      ddl-auto: update